//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoreSoft.MathExpressions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoreSoft.MathExpressions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The IExpression.Evaluate property can not be null. 的本地化字符串。
        /// </summary>
        internal static string EvaluatePropertyCanNotBeNull {
            get {
                return ResourceManager.GetString("EvaluatePropertyCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The function name &apos;{0}&apos; is already registered. 的本地化字符串。
        /// </summary>
        internal static string FunctionNameRegistered {
            get {
                return ResourceManager.GetString("FunctionNameRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number of arguments:  的本地化字符串。
        /// </summary>
        internal static string InvalidArgumentCount {
            get {
                return ResourceManager.GetString("InvalidArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid character:  的本地化字符串。
        /// </summary>
        internal static string InvalidCharacterEncountered {
            get {
                return ResourceManager.GetString("InvalidCharacterEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid convertion expression:  的本地化字符串。
        /// </summary>
        internal static string InvalidConvertionExpression {
            get {
                return ResourceManager.GetString("InvalidConvertionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid function name &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidFunctionName {
            get {
                return ResourceManager.GetString("InvalidFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid length of array. 的本地化字符串。
        /// </summary>
        internal static string InvalidLengthOfArray {
            get {
                return ResourceManager.GetString("InvalidLengthOfArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid math expression. 的本地化字符串。
        /// </summary>
        internal static string InvalidMathExpression {
            get {
                return ResourceManager.GetString("InvalidMathExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number format:  的本地化字符串。
        /// </summary>
        internal static string InvalidNumberFormat {
            get {
                return ResourceManager.GetString("InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid operator:  的本地化字符串。
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid symbol on stack:  的本地化字符串。
        /// </summary>
        internal static string InvalidSymbolOnStack {
            get {
                return ResourceManager.GetString("InvalidSymbolOnStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid function or variable:  的本地化字符串。
        /// </summary>
        internal static string InvalidVariableEncountered {
            get {
                return ResourceManager.GetString("InvalidVariableEncountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number for expression:  的本地化字符串。
        /// </summary>
        internal static string NotEnoughNumbers {
            get {
                return ResourceManager.GetString("NotEnoughNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unbalanced parentheses. 的本地化字符串。
        /// </summary>
        internal static string UnbalancedParentheses {
            get {
                return ResourceManager.GetString("UnbalancedParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The variable name conflicts with function &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string VariableNameConflict {
            get {
                return ResourceManager.GetString("VariableNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The variable name can only contain letters. 的本地化字符串。
        /// </summary>
        internal static string VariableNameContainsLetters {
            get {
                return ResourceManager.GetString("VariableNameContainsLetters", resourceCulture);
            }
        }
    }
}
